# Generated by Django 5.0.1 on 2024-01-15 16:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0002_alter_clothproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothproduct',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapi.clothproduct')),
            ],
        ),
    ]
